const express=require("express");
const app= express();
const morgan=require('morgan');
const cors=require('cors');
const bodyParser = require('body-parser');
app.use(bodyParser.urlencoded({ extended: true }));
app.use(morgan('dev'));
app.use(cors());
app.use(require('./routes/species'));
app.use(require('./routes/animals'));
module.exports=app;